using System;

namespace _31sj
{
    class Program
    {
        static void Main(string[] args)
        {
        bas:

            int toplam = 0, say1 = 0, say2 = 0;
            Console.BackgroundColor = ConsoleColor.Red;
            Console.WriteLine("31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n");
            System.Threading.Thread.Sleep(100);
            Console.ResetColor();
            Console.Clear();
            Console.BackgroundColor = ConsoleColor.Blue;
            Console.WriteLine("31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n");
            System.Threading.Thread.Sleep(100);
            Console.ResetColor();
            Console.Clear();
            Console.BackgroundColor = ConsoleColor.Green;
            Console.WriteLine("31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n");
            System.Threading.Thread.Sleep(100);
            Console.ResetColor();
            Console.Clear();
            Console.BackgroundColor = ConsoleColor.Cyan;
            Console.WriteLine("31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n");
            System.Threading.Thread.Sleep(100);
            Console.ResetColor();
            Console.Clear();
            Console.BackgroundColor = ConsoleColor.Red;
            Console.WriteLine("31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n");
            System.Threading.Thread.Sleep(100);
            Console.ResetColor();
            Console.Clear();
            Console.BackgroundColor = ConsoleColor.Blue;
            Console.WriteLine("31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n");
            System.Threading.Thread.Sleep(100);
            Console.ResetColor();
            Console.Clear();
            Console.BackgroundColor = ConsoleColor.Green;
            Console.WriteLine("31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n");
            System.Threading.Thread.Sleep(100);
            Console.ResetColor();
            Console.Clear();
            Console.BackgroundColor = ConsoleColor.Cyan;
            Console.WriteLine("31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n");
            System.Threading.Thread.Sleep(100);
            Console.ResetColor();
            Console.Clear();
            Console.BackgroundColor = ConsoleColor.Red;
            Console.WriteLine("31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n");
            System.Threading.Thread.Sleep(100);
            Console.ResetColor();
            Console.Clear();
            Console.BackgroundColor = ConsoleColor.Blue;
            Console.WriteLine("31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n");
            System.Threading.Thread.Sleep(100);
            Console.ResetColor();
            Console.Clear();
            Console.BackgroundColor = ConsoleColor.Green;
            Console.WriteLine("31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n");
            System.Threading.Thread.Sleep(100);
            Console.ResetColor();
            Console.Clear();
            Console.BackgroundColor = ConsoleColor.Cyan;
            Console.WriteLine("31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n");
            System.Threading.Thread.Sleep(100);
            Console.ResetColor();
            Console.Clear();
            Console.BackgroundColor = ConsoleColor.Red;
            Console.WriteLine("31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n");
            System.Threading.Thread.Sleep(100);
            Console.ResetColor();
            Console.Clear();
            Console.BackgroundColor = ConsoleColor.Blue;
            Console.WriteLine("31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n");
            System.Threading.Thread.Sleep(100);
            Console.ResetColor();
            Console.Clear();
            Console.BackgroundColor = ConsoleColor.Green;
            Console.WriteLine("31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n");
            System.Threading.Thread.Sleep(100);
            Console.ResetColor();
            Console.Clear();
            Console.BackgroundColor = ConsoleColor.Cyan;
            Console.WriteLine("31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n");
            System.Threading.Thread.Sleep(100);
            Console.ResetColor();
            Console.Clear();
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine("31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n31 Makinesine hoş geldiniz !\n");
            Console.ResetColor();
            System.Threading.Thread.Sleep(500);

            Console.WriteLine("\n Başlamak için yapmak istediğiniz işlemi seçiniz \n--\n 1 - Toplama \n 2- Çıkarma \n 3 - Çarpma \n 4 - Bölme \n 1,2,3,4...");
            Int16 secim1 = Convert.ToInt16(Console.ReadLine());


            Console.WriteLine("\n 1. Sayıyı Giriniz...");
            say1 = Convert.ToInt32(Console.ReadLine());
            Console.WriteLine("\n 2. Sayıyı Giriniz...");
            say2 = Convert.ToInt32(Console.ReadLine());

            switch (secim1)
            {
                case 1:
                    toplam = say1 + say2;
                    break;


                case 2:
                    toplam = say1 - say2;
                    break;

                case 3:
                    toplam = say1 * say2;
                    break;

                case 4:
                    toplam = say1 / say2;
                    break;

            }

            if (toplam == 31)
            {
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("\a BABA 31 ÇIKTI YA WPQCVSADDSFDĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Blue;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();


                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSEREFALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Cyan;
                Console.WriteLine("BABA 31 ÇIKTI YA W213213PQEĞ34324KDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Blue;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSWQEQWEQWEWQEWQDSAALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALSADASDSAD2342345D");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Cyan;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEQ23E214P923859*813123ĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSA123-21*302-3£>]#$}#]|£>}#LD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Blue;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDEWQESALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKD£>$£#$#½>£#$£>$£#½#$½SALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Cyan;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQE21312423RWERĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEWEFSDFFGDFGĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Blue;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSFDSFSDFSDFWEQRWEFSDDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Cyan;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞQWEIPJWQKLEJKLSADJSALKDJSADSAD#£½#$½£#$#£#$£>3214239ASLDKASLŞDJSADKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Blue;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Cyan;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Blue;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Cyan;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Blue;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Cyan;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Blue;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Cyan;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Blue;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Cyan;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Blue;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Cyan;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Blue;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Cyan;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Blue;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Cyan;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");

                System.Threading.Thread.Sleep(300);
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Blue;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Cyan;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Blue;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Cyan;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Blue;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Cyan;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Blue;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Cyan;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Blue;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Cyan;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Blue;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Cyan;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Blue;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Cyan;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Blue;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Cyan;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Blue;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Cyan;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Blue;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Cyan;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Blue;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Cyan;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Blue;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Cyan;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Blue;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Cyan;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Blue;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Cyan;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Blue;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Cyan;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Blue;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Clear();
                Console.ForegroundColor = ConsoleColor.Cyan;
                Console.WriteLine("BABA 31 ÇIKTI YA WPQEĞKDSALD");
                System.Threading.Thread.Sleep(200);
                Console.ResetColor();
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
                Console.Write("xD ");
                System.Threading.Thread.Sleep(300);
            }

            else
            { Console.WriteLine("Toplam sonucunuz : " + toplam); }
            goto bas;
        }
    }
}
